# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(743, 532)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.Barra_Principal = QtWidgets.QFrame(parent=self.frame)
        self.Barra_Principal.setMaximumSize(QtCore.QSize(16777215, 42))
        self.Barra_Principal.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius :20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #2f3136;\n"
"border-radius:100%;\n"
"}")
        self.Barra_Principal.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Barra_Principal.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Barra_Principal.setObjectName("Barra_Principal")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Barra_Principal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label = QtWidgets.QLabel(parent=self.Barra_Principal)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")

        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(601, 17, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.Barra_Principal)
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setText("")

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")

        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(parent=self.Barra_Principal)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")

        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.Barra_Principal)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")

        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addWidget(self.Barra_Principal)
        self.Contenido = QtWidgets.QFrame(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")

        self.Contenido.setFont(font)
        self.Contenido.setStyleSheet("background-color: rgb(47, 49, 54);")
        self.Contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Contenido.setObjectName("Contenido")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Contenido)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.Contenido)
        self.frame_2.setStyleSheet("QPushButton {\n"
"    background-color: #42A5F5; \n"
"    color: white; \n"
"    border: none; \n"
"    border-radius: 8px;\n"
"    padding: 8px 16px; \n"
"    font-size: 14px; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1E88E5; \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1565C0; \n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")

        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light SemiCondensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setKerning(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")

        self.horizontalLayout_2.addWidget(self.frame_2)

        self.frame_3 = QtWidgets.QFrame(parent=self.Contenido)
        self.frame_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")

        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.Contenido)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", " Soundboard"))
        self.pushButton_4.setText(_translate("MainWindow", "Añadir"))
